name: 'Linear Actions'
description: 'GitHub Actions for Linear integration'
author: 'Luke Farrell'

inputs:
  action:
    description: 'The action to run (e.g. get-linear-commits)'
    required: true
  linear-api-key:
    description: 'Linear API Key'
    required: true
  tag-pattern:
    description: 'Tag pattern to match commits (e.g. "release/*")'
    required: true

outputs:
  tickets:
    description: 'Array of Linear tickets'

runs:
  using: 'node20'
  pre: 'dist/pre/index.js'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
  pre-if: 'always()'
  post-if: 'always()'

branding:
  icon: 'ticket'
  color: 'blue' 